version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - book_frontend

networks:
  book_frontend:
    external: true
